export const readerBooks = {
    OL1003017W: {
        workId: "OL1003017W",
        title: "Memórias Póstumas de Brás Cubas",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1881",
        textFile: "/texts/memorias-postumas-de-bras-cubas.txt",
        gutenbergId: "54829",
        sourceUrl: "https://www.gutenberg.org/ebooks/54829",
        allowRomanHeadings: false,
    },
    OL1003040W: {
        workId: "OL1003040W",
        title: "Dom Casmurro",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1899",
        textFile: "/texts/dom-casmurro.txt",
        gutenbergId: "55752",
        sourceUrl: "https://www.gutenberg.org/ebooks/55752",
        allowRomanHeadings: true,
    },
    OL1003079W: {
        workId: "OL1003079W",
        title: "Quincas Borba",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1891",
        textFile: "/texts/quincas-borba.txt",
        gutenbergId: "55682",
        sourceUrl: "https://www.gutenberg.org/ebooks/55682",
        allowRomanHeadings: false,
    },
    OL1525650W: {
        workId: "OL1525650W",
        title: "Iracema",
        author: "José de Alencar",
        authorDeathYear: 1877,
        year: "1865",
        textFile: "/texts/iracema.txt",
        gutenbergId: "67740",
        sourceUrl: "https://www.gutenberg.org/ebooks/67740",
        allowRomanHeadings: false,
    },
    OL7058886W: {
        workId: "OL7058886W",
        title: "O Cortiço",
        author: "Aluísio Azevedo",
        authorDeathYear: 1913,
        year: "1890",
        textFile: "/texts/o-cortico.txt",
        gutenbergId: "69187",
        sourceUrl: "https://www.gutenberg.org/ebooks/69187",
        allowRomanHeadings: false,
    },
    OL1003152W: {
        workId: "OL1003152W",
        title: "Helena",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1876",
        textFile: "/texts/helena.txt",
        gutenbergId: "67162",
        sourceUrl: "https://www.gutenberg.org/ebooks/67162",
        allowRomanHeadings: false,
    },
    OL1003044W: {
        workId: "OL1003044W",
        title: "Esaú e Jacó",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1904",
        textFile: "/texts/esau-e-jaco.txt",
        gutenbergId: "56737",
        sourceUrl: "https://www.gutenberg.org/ebooks/56737",
        allowRomanHeadings: false,
    },
    OL1525648W: {
        workId: "OL1525648W",
        title: "Ubirajara",
        author: "José de Alencar",
        authorDeathYear: 1877,
        year: "1874",
        textFile: "/texts/ubirajara.txt",
        gutenbergId: "38496",
        sourceUrl: "https://www.gutenberg.org/ebooks/38496",
        allowRomanHeadings: true,
    },
    OL2595426W: {
        workId: "OL2595426W",
        title: "O Ateneu",
        author: "Raul Pompeia",
        authorDeathYear: 1895,
        year: "1888",
        textFile: "/texts/o-ateneu.txt",
        gutenbergId: "68541",
        sourceUrl: "https://www.gutenberg.org/ebooks/68541",
        allowRomanHeadings: false,
    },
    OL15371728W: {
        workId: "OL15371728W",
        title: "A Falência",
        author: "Júlia Lopes de Almeida",
        authorDeathYear: 1934,
        year: "1901",
        textFile: "/texts/a-fallencia.txt",
        gutenbergId: "69229",
        sourceUrl: "https://www.gutenberg.org/ebooks/69229",
        allowRomanHeadings: false,
    },
    OL2306387W: {
        workId: "OL2306387W",
        title: "Triste Fim de Policarpo Quaresma",
        author: "Lima Barreto",
        authorDeathYear: 1922,
        year: "1911",
        textFile: "/texts/triste-fim-de-policarpo-quaresma.txt",
        gutenbergId: "67535",
        sourceUrl: "https://www.gutenberg.org/ebooks/67535",
        allowRomanHeadings: true,
    },
    OL4561054W: {
        workId: "OL4561054W",
        title: "Inocência",
        author: "Visconde de Taunay",
        authorDeathYear: 1899,
        year: "1872",
        textFile: "/texts/inocencia.txt",
        gutenbergId: "68635",
        sourceUrl: "https://www.gutenberg.org/ebooks/68635",
        allowRomanHeadings: false,
    },
    OL3422516W: {
        workId: "OL3422516W",
        title: "A Escrava Isaura",
        author: "Bernardo Guimarães",
        authorDeathYear: 1884,
        year: "1875",
        textFile: "/texts/a-escrava-isaura.txt",
        gutenbergId: "74475",
        sourceUrl: "https://www.gutenberg.org/ebooks/74475",
        allowRomanHeadings: false,
    },
};

export function getReaderBook(workId) {
    return readerBooks[workId] || null;
}
