export const readerBooks = {
    OL1003017W: {
        workId: "OL1003017W",
        title: "Memórias Póstumas de Brás Cubas",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1881",
        coverUrl: "/covers/memorias-postumas-de-bras-cubas.webp",
        textFile: "/texts/memorias-postumas-de-bras-cubas.txt",
        gutenbergId: "54829",
        sourceUrl: "https://www.gutenberg.org/ebooks/54829",
        allowRomanHeadings: false,
    },
    OL1003040W: {
        workId: "OL1003040W",
        title: "Dom Casmurro",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1899",
        textFile: "/texts/dom-casmurro.txt",
        gutenbergId: "55752",
        sourceUrl: "https://www.gutenberg.org/ebooks/55752",
        allowRomanHeadings: true,
    },
    OL1003079W: {
        workId: "OL1003079W",
        title: "Quincas Borba",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1891",
        textFile: "/texts/quincas-borba.txt",
        gutenbergId: "55682",
        sourceUrl: "https://www.gutenberg.org/ebooks/55682",
        allowRomanHeadings: false,
    },
    OL1525650W: {
        workId: "OL1525650W",
        title: "Iracema",
        author: "José de Alencar",
        authorDeathYear: 1877,
        year: "1865",
        textFile: "/texts/iracema.txt",
        gutenbergId: "67740",
        sourceUrl: "https://www.gutenberg.org/ebooks/67740",
        allowRomanHeadings: false,
    },
    OL7058886W: {
        workId: "OL7058886W",
        title: "O Cortiço",
        author: "Aluísio Azevedo",
        authorDeathYear: 1913,
        year: "1890",
        textFile: "/texts/o-cortico.txt",
        gutenbergId: "69187",
        sourceUrl: "https://www.gutenberg.org/ebooks/69187",
        allowRomanHeadings: false,
    },
    OL1003152W: {
        workId: "OL1003152W",
        title: "Helena",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1876",
        textFile: "/texts/helena.txt",
        gutenbergId: "67162",
        sourceUrl: "https://www.gutenberg.org/ebooks/67162",
        allowRomanHeadings: false,
    },
    OL1003044W: {
        workId: "OL1003044W",
        title: "Esaú e Jacó",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        year: "1904",
        textFile: "/texts/esau-e-jaco.txt",
        gutenbergId: "56737",
        sourceUrl: "https://www.gutenberg.org/ebooks/56737",
        allowRomanHeadings: false,
    },
    OL1525648W: {
        workId: "OL1525648W",
        title: "Ubirajara",
        author: "José de Alencar",
        authorDeathYear: 1877,
        year: "1874",
        textFile: "/texts/ubirajara.txt",
        gutenbergId: "38496",
        sourceUrl: "https://www.gutenberg.org/ebooks/38496",
        allowRomanHeadings: true,
    },
    OL2595426W: {
        workId: "OL2595426W",
        title: "O Ateneu",
        author: "Raul Pompeia",
        authorDeathYear: 1895,
        year: "1888",
        textFile: "/texts/o-ateneu.txt",
        gutenbergId: "68541",
        sourceUrl: "https://www.gutenberg.org/ebooks/68541",
        allowRomanHeadings: false,
    },
    OL15371728W: {
        workId: "OL15371728W",
        title: "A Falência",
        author: "Júlia Lopes de Almeida",
        authorDeathYear: 1934,
        year: "1901",
        textFile: "/texts/a-fallencia.txt",
        gutenbergId: "69229",
        sourceUrl: "https://www.gutenberg.org/ebooks/69229",
        allowRomanHeadings: false,
    },
    OL2306387W: {
        workId: "OL2306387W",
        title: "Triste Fim de Policarpo Quaresma",
        author: "Lima Barreto",
        authorDeathYear: 1922,
        year: "1911",
        textFile: "/texts/triste-fim-de-policarpo-quaresma.txt",
        gutenbergId: "67535",
        sourceUrl: "https://www.gutenberg.org/ebooks/67535",
        allowRomanHeadings: true,
    },
    OL4561054W: {
        workId: "OL4561054W",
        title: "Inocência",
        author: "Visconde de Taunay",
        authorDeathYear: 1899,
        year: "1872",
        textFile: "/texts/inocencia.txt",
        gutenbergId: "68635",
        sourceUrl: "https://www.gutenberg.org/ebooks/68635",
        allowRomanHeadings: false,
    },
    OL3422516W: {
        workId: "OL3422516W",
        title: "A Escrava Isaura",
        author: "Bernardo Guimarães",
        authorDeathYear: 1884,
        year: "1875",
        textFile: "/texts/a-escrava-isaura.txt",
        gutenbergId: "74475",
        sourceUrl: "https://www.gutenberg.org/ebooks/74475",
        allowRomanHeadings: false,
    },
    PG2837: {
        workId: "PG2837",
        title: "Lendas do Sul",
        author: "João Simões Lopes Neto",
        authorDeathYear: 1916,
        textFile: "/texts/lendas-do-sul.txt",
        gutenbergId: "2837",
        sourceUrl: "https://www.gutenberg.org/ebooks/2837",
        allowRomanHeadings: false,
    },
    PG28691: {
        workId: "PG28691",
        title: "Contos do Norte",
        author: "João Marques de Carvalho",
        authorDeathYear: 1910,
        textFile: "/texts/contos-do-norte.txt",
        gutenbergId: "28691",
        sourceUrl: "https://www.gutenberg.org/ebooks/28691",
        allowRomanHeadings: false,
    },
    PG29040: {
        workId: "PG29040",
        title: "Como e Por Que Sou Romancista",
        author: "José de Alencar",
        authorDeathYear: 1877,
        textFile: "/texts/como-e-porque-sou-romancista.txt",
        gutenbergId: "29040",
        sourceUrl: "https://www.gutenberg.org/ebooks/29040",
        allowRomanHeadings: false,
    },
    PG29161: {
        workId: "PG29161",
        title: "Entre as Nymphéas",
        author: "João Marques de Carvalho",
        authorDeathYear: 1910,
        textFile: "/texts/entre-as-nympheas.txt",
        gutenbergId: "29161",
        sourceUrl: "https://www.gutenberg.org/ebooks/29161",
        allowRomanHeadings: false,
    },
    PG30341: {
        workId: "PG30341",
        title: "Contos Paraenses",
        author: "João Marques de Carvalho",
        authorDeathYear: 1910,
        textFile: "/texts/contos-paraenses.txt",
        gutenbergId: "30341",
        sourceUrl: "https://www.gutenberg.org/ebooks/30341",
        allowRomanHeadings: false,
    },
    PG33056: {
        workId: "PG33056",
        title: "Histórias sem Data",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/historias-sem-data.txt",
        gutenbergId: "33056",
        sourceUrl: "https://www.gutenberg.org/ebooks/33056",
        allowRomanHeadings: false,
    },
    PG33611: {
        workId: "PG33611",
        title: "Cenas de Viagem",
        author: "Visconde de Taunay",
        authorDeathYear: 1899,
        textFile: "/texts/cenas-de-viagem.txt",
        gutenbergId: "33611",
        sourceUrl: "https://www.gutenberg.org/ebooks/33611",
        allowRomanHeadings: false,
    },
    PG34750: {
        workId: "PG34750",
        title: "Mistério do Natal",
        author: "Coelho Netto",
        authorDeathYear: 1934,
        textFile: "/texts/misterio-do-natal.txt",
        gutenbergId: "34750",
        sourceUrl: "https://www.gutenberg.org/ebooks/34750",
        allowRomanHeadings: false,
    },
    PG44540: {
        workId: "PG44540",
        title: "Cinco Minutos",
        author: "José de Alencar",
        authorDeathYear: 1877,
        textFile: "/texts/cinco-minutos.txt",
        gutenbergId: "44540",
        sourceUrl: "https://www.gutenberg.org/ebooks/44540",
        allowRomanHeadings: false,
    },
    PG53101: {
        workId: "PG53101",
        title: "A Mão e a Luva",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/a-mao-e-a-luva.txt",
        gutenbergId: "53101",
        sourceUrl: "https://www.gutenberg.org/ebooks/53101",
        allowRomanHeadings: false,
    },
    PG55797: {
        workId: "PG55797",
        title: "Memorial de Ayres",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/memorial-de-ayres.txt",
        gutenbergId: "55797",
        sourceUrl: "https://www.gutenberg.org/ebooks/55797",
        allowRomanHeadings: false,
    },
    PG57001: {
        workId: "PG57001",
        title: "Papéis Avulsos",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/papeis-avulsos.txt",
        gutenbergId: "57001",
        sourceUrl: "https://www.gutenberg.org/ebooks/57001",
        allowRomanHeadings: false,
    },
    PG61653: {
        workId: "PG61653",
        title: "Poesias Completas",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/poesias-completas.txt",
        gutenbergId: "61653",
        sourceUrl: "https://www.gutenberg.org/ebooks/61653",
        allowRomanHeadings: false,
    },
    PG62525: {
        workId: "PG62525",
        title: "Histórias Brasileiras",
        author: "Visconde de Taunay",
        authorDeathYear: 1899,
        textFile: "/texts/historias-brasileiras.txt",
        gutenbergId: "62525",
        sourceUrl: "https://www.gutenberg.org/ebooks/62525",
        allowRomanHeadings: false,
    },
    PG62896: {
        workId: "PG62896",
        title: "Ao Entardecer: Contos Vários",
        author: "Visconde de Taunay",
        authorDeathYear: 1899,
        textFile: "/texts/ao-entardecer.txt",
        gutenbergId: "62896",
        sourceUrl: "https://www.gutenberg.org/ebooks/62896",
        allowRomanHeadings: false,
    },
    PG63606: {
        workId: "PG63606",
        title: "Lupe",
        author: "Affonso Celso",
        authorDeathYear: 1938,
        textFile: "/texts/lupe.txt",
        gutenbergId: "63606",
        sourceUrl: "https://www.gutenberg.org/ebooks/63606",
        allowRomanHeadings: false,
    },
    PG67594: {
        workId: "PG67594",
        title: "A Intrusa",
        author: "Júlia Lopes de Almeida",
        authorDeathYear: 1934,
        textFile: "/texts/a-intrusa.txt",
        gutenbergId: "67594",
        sourceUrl: "https://www.gutenberg.org/ebooks/67594",
        allowRomanHeadings: false,
    },
    PG67724: {
        workId: "PG67724",
        title: "O Guarani — Volume I",
        author: "José de Alencar",
        authorDeathYear: 1877,
        textFile: "/texts/o-guarani-volume-1.txt",
        gutenbergId: "67724",
        sourceUrl: "https://www.gutenberg.org/ebooks/67724",
        allowRomanHeadings: false,
    },
    PG67725: {
        workId: "PG67725",
        title: "O Guarani — Volume II",
        author: "José de Alencar",
        authorDeathYear: 1877,
        textFile: "/texts/o-guarani-volume-2.txt",
        gutenbergId: "67725",
        sourceUrl: "https://www.gutenberg.org/ebooks/67725",
        allowRomanHeadings: false,
    },
    PG67780: {
        workId: "PG67780",
        title: "Yayá Garcia",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/yaya-garcia.txt",
        gutenbergId: "67780",
        sourceUrl: "https://www.gutenberg.org/ebooks/67780",
        allowRomanHeadings: false,
    },
    PG67831: {
        workId: "PG67831",
        title: "A Pata da Gazela",
        author: "José de Alencar",
        authorDeathYear: 1877,
        textFile: "/texts/a-pata-da-gazela.txt",
        gutenbergId: "67831",
        sourceUrl: "https://www.gutenberg.org/ebooks/67831",
        allowRomanHeadings: false,
    },
    PG67935: {
        workId: "PG67935",
        title: "Relíquias de Casa Velha",
        author: "Machado de Assis",
        authorDeathYear: 1908,
        textFile: "/texts/reliquias-de-casa-velha.txt",
        gutenbergId: "67935",
        sourceUrl: "https://www.gutenberg.org/ebooks/67935",
        allowRomanHeadings: false,
    },
    PG69239: {
        workId: "PG69239",
        title: "Era uma vez…",
        author: "Júlia Lopes de Almeida",
        authorDeathYear: 1934,
        textFile: "/texts/era-uma-vez.txt",
        gutenbergId: "69239",
        sourceUrl: "https://www.gutenberg.org/ebooks/69239",
        allowRomanHeadings: false,
    },
    PG70121: {
        workId: "PG70121",
        title: "A Capital Federal",
        author: "Coelho Netto",
        authorDeathYear: 1934,
        textFile: "/texts/a-capital-federal.txt",
        gutenbergId: "70121",
        sourceUrl: "https://www.gutenberg.org/ebooks/70121",
        allowRomanHeadings: false,
    },
    PG71724: {
        workId: "PG71724",
        title: "Obras Poéticas de Gregório de Matos — Tomo I",
        author: "Gregório de Matos",
        authorDeathYear: 1696,
        textFile: "/texts/obras-poeticas-gregorio-de-matos.txt",
        gutenbergId: "71724",
        sourceUrl: "https://www.gutenberg.org/ebooks/71724",
        allowRomanHeadings: false,
    },
    PG74854: {
        workId: "PG74854",
        title: "Cantos",
        author: "Gonçalves Dias",
        authorDeathYear: 1864,
        textFile: "/texts/cantos.txt",
        gutenbergId: "74854",
        sourceUrl: "https://www.gutenberg.org/ebooks/74854",
        allowRomanHeadings: false,
    },
    PG28639: {
        workId: "PG28639",
        title: "Talitha: Evangelho em Três Atos",
        author: "Pinto da Rocha",
        authorDeathYear: 1930,
        textFile: "/texts/talitha.txt",
        gutenbergId: "28639",
        sourceUrl: "https://www.gutenberg.org/ebooks/28639",
        allowRomanHeadings: false,
    },
    WS1001: {
        workId: "WS1001",
        title: "Eu",
        author: "Augusto dos Anjos",
        authorDeathYear: 1914,
        year: "1912",
        textFile: "/texts/eu-augusto-dos-anjos.txt",
        sourceName: "Wikisource",
        sourceEdition: "Eu (1912), edição de referência do Rio de Janeiro",
        sourceUrl: "https://pt.wikisource.org/wiki/Eu_(Augusto_dos_Anjos,_1912)",
        sourceLicense: "CC BY-SA 4.0",
        sourceLicenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR",
        sourceExportUrl: "https://ws-export.wmcloud.org/?lang=pt&format=epub&page=Eu_(Augusto_dos_Anjos,_1912)",
        preserveLineBreaks: true,
    },
    WS1002: {
        workId: "WS1002",
        title: "Úrsula",
        author: "Maria Firmina dos Reis",
        authorDeathYear: 1917,
        year: "1859",
        textFile: "/texts/ursula-maria-firmina-dos-reis.txt",
        sourceName: "Wikisource",
        sourceEdition: "Úrsula, Typographia do Progresso, 1859",
        sourceUrl: "https://pt.wikisource.org/wiki/%C3%9Arsula",
        sourceLicense: "CC BY-SA 4.0",
        sourceLicenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR",
        sourceExportUrl: "https://ws-export.wmcloud.org/?lang=pt&format=epub&page=%C3%9Arsula",
        preserveLineBreaks: false,
    },
};

export function getReaderBook(workId) {
    return readerBooks[workId] || null;
}
